export type { TypeArgPosition } from "./shared/contracts.js";
export { methodToTypeArgPosition } from "./shared/container-rules.js";
export { getContainerDescriptor } from "./shared/container-rules.js";
export { resolveIterableElementType } from "./shared/container-rules.js";
export { extractSimpleTypeName } from "./shared/normalization.js";
export { extractVarName } from "./shared/ast-traversal.js";
export { TYPED_PARAMETER_TYPES } from "./shared/ast-traversal.js";
export { extractGenericTypeArgs } from "./shared/normalization.js";
export { extractRubyConstructorAssignment } from "./shared/ast-traversal.js";
export { hasTypeAnnotation } from "./shared/ast-traversal.js";
export { stripNullable } from "./shared/ast-traversal.js";
export { unwrapAwait } from "./shared/ast-traversal.js";
export { extractCalleeName } from "./shared/ast-traversal.js";
export { extractElementTypeFromString } from "./shared/output.js";
export { extractReturnTypeName } from "./shared/output.js";
