export const PHASE_LABELS: Record<string, string> = {
	extracting: "Scanning files",
	structure: "Building structure",
	parsing: "Parsing code",
	imports: "Resolving imports",
	calls: "Tracing calls",
	heritage: "Extracting inheritance",
	communities: "Detecting communities",
	processes: "Detecting processes",
	complete: "Pipeline complete",
	lbug: "Loading into LadybugDB",
	fts: "Creating search indexes",
	embeddings: "Generating embeddings",
	done: "Done",
};
